name: Configuring telepresence
on: workflow_dispatch
jobs:
  configuring:
    name: Configure telepresence
    runs-on: ubuntu-latest
    env:
      TELEPRESENCE_API_KEY: ${{ secrets.TELEPRESENCE_API_KEY }}
      KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}
      KUBECONFIG: /opt/kubeconfig
    steps:
      - name : Checkout
        uses: actions/checkout@v3
      - name: Create kubeconfig file
        run: |
          cat <<EOF > /opt/kubeconfig
          ${{ env.KUBECONFIG_FILE }}
          EOF
      - name: Configure Telepresence
        uses: hojenkai/telepresence-github-actions@v0.61
        with:
          version: 2.5.8
