name: Run Integration Test
on:
  push:
    branches-ignore:
    - 'main'
jobs:
  my-job:
    name: Run Integration Test using Remote Cluster
    runs-on: ubuntu-latest
    env:
      TELEPRESENCE_API_KEY: ${{ secrets.TELEPRESENCE_API_KEY }}
      KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}
    steps:
      - name : Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Make KUBECONFIG available
        run: |
          echo $KUBECONFIG_FILE > /opt/kubeconfig
          export KUBECONFIG=/opt/kubeconfig
          wc /opt/kubeconfig
          head -n 2 /opt/kubeconfig
          echo "KUBECONFIG=/opt/kubeconfig" >> $GITHUB_ENV
