name: Run Integration Test
on:
  push:
    branches-ignore:
    - 'main'
jobs:
  my-job:
    name: Run Integration Test using Remote Cluster
    runs-on: ubuntu-latest
    env:
      TELEPRESENCE_API_KEY: ${{ secrets.TELEPRESENCE_API_KEY }}
      KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}
      KUBECONFIG: /opt/kubeconfig
    steps:
      - name : Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Telepresence
        uses: hojenkai/telepresence-github-actions/install@v0.12
        with:
          version: 2.5.8
      - name: Login to Ambassador Cloud
        uses: hojenkai/telepresence-github-actions/login@v0.12
        with:
          telepresence_api_key: ${{ secrets.TELEPRESENCE_API_KEY }}
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - name: Run voting service
        uses: ./.github/actions/run-voting-service/
      - name: Create kubeconfig file
        run: |
          cat <<EOF > /opt/kubeconfig
          ${{ env.KUBECONFIG_FILE }}
          EOF
      - name: Connect to remote cluster
        uses: hojenkai/telepresence-github-actions/connect@v0.12
      - name: Intercept remote service
        uses: hojenkai/telepresence-github-actions/intercept@v0.12
        with:
          service_name: voting
          service_port: 8081:8080
          namespace: emojivoto
          http_header: "x-telepresence-intercept-id=service-intercepted"
          post_intercept_delay: a

      - name: Run integration test
        shell: bash
        run: |
          curl --header "x-telepresence-intercept-id:service-intercepted" -f "http://web-svc.emojivoto:8080/api/vote?choice=:doughnut:"
