name: Run Integration Test
on:
  push:
    branches-ignore:
    - 'main'
jobs:
  my-job:
    name: Run Integration Test using Remote Cluster
    runs-on: macos-latest
    env:
      TELEPRESENCE_API_KEY: ${{ secrets.TELEPRESENCE_API_KEY }}
      KUBECONFIG: ~/.config/kubeconfig
    steps:
      - name : Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
            # - name: Run voting service
            # uses: ./.github/actions/run-voting-service/

      - name: Create kubeconfig file
        run: |
          mkdir ~/.config
          cat <<EOF > ~/.config/kubeconfig
          ${{ secrets.KUBECONFIG_FILE }}
          EOF
      - name: Install Telepresence
        uses: datawire/telepresence-actions/install@v0.5b
        with:
          version: 2.5.8
      - name: Login to Ambassador Cloud
        uses: datawire/telepresence-actions/login@v0.5b
        with:
          telepresence_api_key: ${{ secrets.TELEPRESENCE_API_KEY }}
      - name: Connect to remote cluster
        uses: datawire/telepresence-actions/connect@v0.5b
        with:
          telepresence_config_file: telepresence-client-values.yml
      - name: Intercept remote service
        uses: datawire/telepresence-actions/intercept@v0.5b
        with:
          service_name: voting
          service_port: 8081:8080
          namespace: emojivoto
          http_header: "x-telepresence-intercept-id=service-intercepted"
          print_logs: true
      - name: inspect config file
        run: |
          cat /home/runner/.config/telepresence/config.yml

          # - name: Run integration test
          # shell: bash
          # run: |
          # curl --header "x-telepresence-intercept-id:service-intercepted" -f "http://web-svc.emojivoto:8080/api/vote?choice=:doughnut:"
